image: openjdk:23
stages:
  - build
  - test
  - deploy

before_script:
  - apt-get update
  - apt-get install -y xargs

build:
  stage: build
  script:
    - chmod +x ./gradlew
    - ./gradlew jibBuild
  artifacts:
    paths:
      - build/jib-image.tar

test:
  stage: test
  script:
    - ./gradlew test


deploy:
  stage: deploy
  script:
    - kubectl port-forward -n default svc/hello-k8s-svc 8080:8080 &
    - kubectl apply -f src/k8s/deployment.yaml
    - kubectl apply -f src/k8s/service.yaml
  environment:
    name: local
    url: http://localhost:8080