image: openjdk:23

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

stages:
  - build
  - test
  - deploy

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script:
    - ./gradlew jibBuild
  artifacts:
    paths:
      - build/jib-image.tar

test:
  stage: test
  script:
    - ./gradlew test

deploy:
  stage: deploy
  script:
    - kubectl port-forward -n default svc/hello-k8s-svc 8080:8080 &
    - kubectl apply -f src/k8s/deployment.yaml
    - kubectl apply -f src/k8s/service.yaml
  environment:
    name: local
    url: http://localhost:8080