image: gradle:jdk23-alpine

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

build:
  stage: build
  script: gradle jibBuild --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build/jib-image.tar/*.tar
      - .gradle

test:
  stage: test
  script: gradle check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

deploy:
  stage: deploy
  script:
    - kubectl port-forward -n default svc/hello-k8s-svc 8080:8080 &
    - kubectl apply -f src/k8s/deployment.yaml
    - kubectl apply -f src/k8s/service.yaml
  environment:
    name: local
    url: http://localhost:8080